# Generated by Django 5.0.6 on 2024-08-01 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_telegram_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_bsc_derivation_path',
        ),
    ]
