# Generated by Django 5.0.6 on 2024-07-25 12:01

import web.applications.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=web.applications.core.models.PathAndRename('wallet/token/logo'), verbose_name='Token logo'),
        ),
    ]
