# Generated by Django 5.0.6 on 2024-07-25 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_token_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='description',
        ),
        migrations.AddField(
            model_name='token',
            name='logo_url',
            field=models.URLField(blank=True, verbose_name='Token logo url'),
        ),
    ]
