# Generated by Django 5.0.6 on 2024-07-25 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_remove_token_description_token_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='freeze_authority',
            field=models.CharField(blank=True, max_length=100, verbose_name='Freeze authority'),
        ),
        migrations.AlterField(
            model_name='token',
            name='metadata_account',
            field=models.CharField(blank=True, max_length=100, verbose_name='Metadata account'),
        ),
        migrations.AlterField(
            model_name='token',
            name='mint_account',
            field=models.CharField(max_length=100, unique=True, verbose_name='Mint account'),
        ),
        migrations.AlterField(
            model_name='token',
            name='mint_authority',
            field=models.CharField(blank=True, max_length=100, verbose_name='Mint authority'),
        ),
        migrations.AlterField(
            model_name='token',
            name='token_account',
            field=models.CharField(blank=True, max_length=100, verbose_name='Token account'),
        ),
    ]
