# Generated by Django 5.0.6 on 2024-07-29 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_alter_token_freeze_authority_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hdwallet',
            name='blockchain',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='blockchain',
        ),
    ]
